In [18]:
import pandas as pd

In [19]:
!pip install xgboost

Collecting xgboost
  Using cached xgboost-3.1.2-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\tushar bhardwaj\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\tushar bhardwaj\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from xgboost) (1.11.4)
Downloading xgboost-3.1.2-py3-none-win_amd64.whl (72.0 MB)
   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
    --------------------------------------- 1.0/72.0 MB 6.3 MB/s eta 0:00:12
   - -------------------------------------- 1.8/72.0 MB 5.3 MB/s eta 0:00:14
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.1/72.0 MB 5.4 MB/s eta 0:00:13
   - -------------------------------------- 3.2/72.0 MB 522.0 kB/s eta 0:02:12

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\tushar bhardwaj\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 e627c50003269b4562aa611ed348dff8cb770e11a9f784b3888a43139a0f5073
             Got        a88942e4a2715a86cdd0c4f68f8e807f72a9249b47d02807994402377fdd35e5

In [21]:
from pycaret.datasets import get_data
import pandas as pd

df = get_data('juice')   # Built-in churn dataset
df.head()

,Id,Purchase,WeekofPurchase,StoreID,PriceCH,PriceMM,DiscCH,DiscMM,SpecialCH,SpecialMM,LoyalCH,SalePriceMM,SalePriceCH,PriceDiff,Store7,PctDiscMM,PctDiscCH,ListPriceDiff,STORE
0,1,CH,237,1,1.75,1.99,0.00,0.0,0,0,0.500000,1.99,1.75,0.24,No,0.000000,0.000000,0.24,1
1,2,CH,239,1,1.75,1.99,0.00,0.3,0,1,0.600000,1.69,1.75,-0.06,No,0.150754,0.000000,0.24,1
2,3,CH,245,1,1.86,2.09,0.17,0.0,0,0,0.680000,2.09,1.69,0.40,No,0.000000,0.091398,0.23,1
3,4,MM,227,1,1.69,1.69,0.00,0.0,0,0,0.400000,1.69,1.69,0.00,No,0.000000,0.000000,0.00,1
4,5,CH,228,7,1.69,1.69,0.00,0.0,0,0,0.956535,1.69,1.69,0.00,Yes,0.000000,0.000000,0.00,0

,Id,Purchase,WeekofPurchase,StoreID,PriceCH,PriceMM,DiscCH,DiscMM,SpecialCH,SpecialMM,LoyalCH,SalePriceMM,SalePriceCH,PriceDiff,Store7,PctDiscMM,PctDiscCH,ListPriceDiff,STORE
0,1,CH,237,1,1.75,1.99,0.00,0.0,0,0,0.500000,1.99,1.75,0.24,No,0.000000,0.000000,0.24,1
1,2,CH,239,1,1.75,1.99,0.00,0.3,0,1,0.600000,1.69,1.75,-0.06,No,0.150754,0.000000,0.24,1
2,3,CH,245,1,1.86,2.09,0.17,0.0,0,0,0.680000,2.09,1.69,0.40,No,0.000000,0.091398,0.23,1
3,4,MM,227,1,1.69,1.69,0.00,0.0,0,0,0.400000,1.69,1.69,0.00,No,0.000000,0.000000,0.00,1
4,5,CH,228,7,1.69,1.69,0.00,0.0,0,0,0.956535,1.69,1.69,0.00,Yes,0.000000,0.000000,0.00,0

In [22]:
# Convert TotalCharges to numeric
from pycaret.datasets import get_data
df = get_data('juice')
df.head()

,Id,Purchase,WeekofPurchase,StoreID,PriceCH,PriceMM,DiscCH,DiscMM,SpecialCH,SpecialMM,LoyalCH,SalePriceMM,SalePriceCH,PriceDiff,Store7,PctDiscMM,PctDiscCH,ListPriceDiff,STORE
0,1,CH,237,1,1.75,1.99,0.00,0.0,0,0,0.500000,1.99,1.75,0.24,No,0.000000,0.000000,0.24,1
1,2,CH,239,1,1.75,1.99,0.00,0.3,0,1,0.600000,1.69,1.75,-0.06,No,0.150754,0.000000,0.24,1
2,3,CH,245,1,1.86,2.09,0.17,0.0,0,0,0.680000,2.09,1.69,0.40,No,0.000000,0.091398,0.23,1
3,4,MM,227,1,1.69,1.69,0.00,0.0,0,0,0.400000,1.69,1.69,0.00,No,0.000000,0.000000,0.00,1
4,5,CH,228,7,1.69,1.69,0.00,0.0,0,0,0.956535,1.69,1.69,0.00,Yes,0.000000,0.000000,0.00,0

,Id,Purchase,WeekofPurchase,StoreID,PriceCH,PriceMM,DiscCH,DiscMM,SpecialCH,SpecialMM,LoyalCH,SalePriceMM,SalePriceCH,PriceDiff,Store7,PctDiscMM,PctDiscCH,ListPriceDiff,STORE
0,1,CH,237,1,1.75,1.99,0.00,0.0,0,0,0.500000,1.99,1.75,0.24,No,0.000000,0.000000,0.24,1
1,2,CH,239,1,1.75,1.99,0.00,0.3,0,1,0.600000,1.69,1.75,-0.06,No,0.150754,0.000000,0.24,1
2,3,CH,245,1,1.86,2.09,0.17,0.0,0,0,0.680000,2.09,1.69,0.40,No,0.000000,0.091398,0.23,1
3,4,MM,227,1,1.69,1.69,0.00,0.0,0,0,0.400000,1.69,1.69,0.00,No,0.000000,0.000000,0.00,1
4,5,CH,228,7,1.69,1.69,0.00,0.0,0,0,0.956535,1.69,1.69,0.00,Yes,0.000000,0.000000,0.00,0

In [23]:
from pycaret.classification import *

exp = setup(data=df,
            target='Purchase',
            session_id=123,
            normalize=True,
            train_size=0.8,
            fold=5)

In [24]:
best_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
model = create_model('xgboost')
tuned_model = tune_model(model)

In [ ]:
evaluate_model(tuned_model)

In [ ]:
save_model(tuned_model, 'churn_model_pycaret')
loaded_model = load_model('churn_model_pycaret')
predict_model(loaded_model, data=df)
df_pred = predict_model(tuned_model, data=df)
df_pred[['Churn', 'prediction_label', 'prediction_score']].head()